base_url = "https://mafterning.com"
title = "mafterning.com"
description = "A blog about technology, programming, and other musings"
build_search_index = true
generate_feeds = true
compile_sass = true
minify_html = true
theme = "apollo"
taxonomies = [{ name = "tags" }]

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[markdown]
highlight_code = true
highlight_theme = "ayu-light"

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "toggle"
fancy_code = true
dynamic_note = true
mathjax = true
mathjax_dollar_inline_enable = true

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/about", url = "/about", weight = 2 },
    { name = "/tags", url = "/tags", weight = 3 },
]

socials = [
    # Add your social links here
    # { name = "github", url = "https://github.com/your-username", icon = "github" },
]

[extra.analytics]
enabled = false